server:
  port: 8080

spring:
  application:
    name: micro-dept-provider-8080
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.140.88/test
    driver-class-name: com.mysql.jdbc.Driver #todo：数据源的配置：4个


mybatis:
  config-location: classpath:/mybatis/mybatisConfig.xml
  type-aliases-package: com.yunque.www.springbootdemo.pojo
  mapper-locations:
  - classpath:/mybatis/mapper/**/*.xml

#添加Eureka客户端的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

  instance:
    #1）修改“微服务的名称”
    instance-id: micro-dept-customer-8001
    #2）显示当前微服务所在的ip地址
    prefer-ip-address: true

info:
  app.name: yunquedeptmicro
  company.name: www.yunque.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$










